name = "unmask-supabase"
main = "src/index.ts"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
database_id = "d6f7a69916c6466ab2bc8663361bf2ad"

[vars]
SUPABASE_URL = "https://dsnsuagkzkuzzjwvuomi.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzbnN1YWdremt1enpqd3Z1b21pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNDY1MTQsImV4cCI6MjA1OTYyMjUxNH0.HN5rZs0oaoZGoppTLJjMUlis2qEDjq2_RWs8Q3mtqjc"